### ISSUE TITLE
bot端启动失败

### ISSUE THREAD

**Issue by FYSH2003** [CikeyQi/mc-plugin#12]
[MiaoYz][14:06:56.678][INFO] 【Minecraft-Plugin v1.0.1】 [MC_QQ]丨WebSocket 服务器已启动，等待连接
[MiaoYz][14:06:56.679][INFO] ---------------
[MiaoYz][14:06:56.680][MARK] Minecraft WebSocket 地址：ws://127.0.0.1:9090/yz/v3/mcqq
[MiaoYz][14:06:56.681][INFO] ---------------
node:buffer:787
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (114514)
    at new NodeError (node:internal/errors:405:5)
    at Function.byteLength (node:buffer:787:11)
    at Rcon.send (C:\Users\Administrator\Desktop\QQG\Miao-Yunzai\node_modules\.pnpm\rcon@1.1.0\node_modules\rcon\node-rcon.js:51:25)
    at Rcon.socketOnConnect (C:\Users\Administrator\Desktop\QQG\Miao-Yunzai\node_modules\.pnpm\rcon@1.1.0\node_modules\rcon\node-rcon.js:196:10)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\QQG\Miao-Yunzai\node_modules\.pnpm\rcon@1.1.0\node_modules\rcon\node-rcon.js:88:53)
    at Socket.emit (node:events:526:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1480:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.17.1

**Comment by CikeyQi** [comment]
rcon_password: '114514'，使请使用引号将纯数字密码包起来，以确保为字符串格式
