### ISSUE TITLE
有概率获取群对象失败

### ISSUE THREAD

**Issue by CuteLittleSky** [CikeyQi/mc-plugin#21]
获取群对象失败：找不到群 ————
file:///D:/Yunzai/plugins/mc-plugin/components/WebSocket.js:92
        Bot.pickGroup(config.group_list[i]).sendMsg(msg);
                                           ^

TypeError: Cannot read properties of undefined (reading 'sendMsg')
    at WebSocket.sendMsg (file:///D:/Yunzai/plugins/mc-plugin/components/WebSocket.js:92:44)
    at WebSocketServer.<anonymous> (file:///D:/Yunzai/plugins/mc-plugin/components/WebSocket.js:36:16)
    at WebSocketServer.emit (node:events:514:28)
    at WebSocketServer.completeUpgrade (D:\Yunzai\node_modules\.pnpm\ws@8.14.2\node_modules\ws\lib\websocket-server.js:427:5)
    at WebSocketServer.handleUpgrade (D:\Yunzai\node_modules\.pnpm\ws@8.14.2\node_modules\ws\lib\websocket-server.js:336:10)
    at Server.upgrade (D:\Yunzai\node_modules\.pnpm\ws@8.14.2\node_modules\ws\lib\websocket-server.js:112:16)
    at Server.emit (node:events:514:28)
    at onParserExecuteCommon (node:_http_server:942:14)
    at onParserExecute (node:_http_server:836:3)

但是多登几次就好了..

**Comment by CikeyQi** [comment]
也许是适配器的原因？
