### ISSUE TITLE
非插件端只能单向推送信息

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [CikeyQi/mc-plugin#6]
QQ群→MC服务器成功
MC服务器→QQ群 失败

MC服务器日志
```
[MC_QQ]丨已成功连接 WebSocket 服务器。
[MC_QQ]丨Lemon_ZSH说：娉ョ尨
[MC_QQ]丨Lemon_ZSH说：娴嬬爜
[MC_QQ]丨Shirasu_Azusa09说：绌哄惂鍝�
[MC_QQ] 日志路径错误，无法读取。
java.lang.NullPointerException: Cannot invoke "java.util.regex.Matcher.group(int)" because "serverLog" is null
        at com.scareye.mcqq.Utils.processMessageToJson(Utils.java:132)
        at com.scareye.mcqq.FileWatcher.lambda$watcherLog$4(FileWatcher.java:100)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.scareye.mcqq.FileWatcher.watcherLog(FileWatcher.java:83)
        at com.scareye.mcqq.FileWatcher.lambda$FileListen$1(FileWatcher.java:37)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
只能传递这一条消息，而且读取到的中文是乱码，后面还有报错
![7G Z8CSYJ`I7E91PR62CX23](https://github.com/CikeyQi/mc-plugin/assets/38343280/ab4f6db7-b501-4ce2-9548-4a0a1f7fcf06)

MC服务器配置文件
```
enable_mc_qq: true
websocket_url: "ws://云崽服务器IP:9090/yz/v3/mcqq"
say_way: "说："
death_message: true
join_quit: true
server_name: "Server"
display_groupname: false
log_local: "./logs/"
log_name: "latest.log"
```

云崽配置文件
```
mc_qq_ws_url: /yz/v3/mcqq
mc_qq_ws_port: 9090
mc_qq_send_group_name: false
rcon_enable: true
rcon_host: MC服务器地址
rcon_port: 25575
rcon_password: "12300"
group_list:
  - 群号
```

**Comment by ShoukakuChuuCC** [comment]
应该去服务端程序上游发的 不好意思

**Comment by Msg-Lbo** [comment]
> QQ群→MC服务器成功 MC服务器→QQ群 失败
> 
> MC服务器日志
> 
> ```
> [MC_QQ]丨已成功连接 WebSocket 服务器。
> [MC_QQ]丨Lemon_ZSH说：娉ョ尨
> [MC_QQ]丨Lemon_ZSH说：娴嬬爜
> [MC_QQ]丨Shirasu_Azusa09说：绌哄惂鍝�
> [MC_QQ] 日志路径错误，无法读取。
> java.lang.NullPointerException: Cannot invoke "java.util.regex.Matcher.group(int)" because "serverLog" is null
>         at com.scareye.mcqq.Utils.processMessageToJson(Utils.java:132)
>         at com.scareye.mcqq.FileWatcher.lambda$watcherLog$4(FileWatcher.java:100)
>         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
>         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
>         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
>         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
>         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
>         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
>         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
>         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
>         at com.scareye.mcqq.FileWatcher.watcherLog(FileWatcher.java:83)
>         at com.scareye.mcqq.FileWatcher.lambda$FileListen$1(FileWatcher.java:37)
>         at java.base/java.lang.Thread.run(Thread.java:833)
> ```
> 
> 只能传递这一条消息，而且读取到的中文是乱码，后面还有报错 ![7G Z8CSYJ`I7E91PR62CX23](https://user-images.githubusercontent.com/38343280/261342860-ab4f6db7-b501-4ce2-9548-4a0a1f7fcf06.png)
> 
> MC服务器配置文件
> 
> ```
> enable_mc_qq: true
> websocket_url: "ws://云崽服务器IP:9090/yz/v3/mcqq"
> say_way: "说："
> death_message: true
> join_quit: true
> server_name: "Server"
> display_groupname: false
> log_local: "./logs/"
> log_name: "latest.log"
> ```
> 
> 云崽配置文件
> 
> ```
> mc_qq_ws_url: /yz/v3/mcqq
> mc_qq_ws_port: 9090
> mc_qq_send_group_name: false
> rcon_enable: true
> rcon_host: MC服务器地址
> rcon_port: 25575
> rcon_password: "12300"
> group_list:
>   - 群号
> ```

我也遇到了这个问题，请问是如何解决的呀

**Comment by RyanJiang184** [comment]
同
